version: '3.8'


services:
  flask-app:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - "./scores.txt:/scores.txt"
