# Use the official Python image from the Docker Hub
FROM python:3.9-alpine

# Set a working directory
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code into the container
COPY main_score.py .

# Expose the port that Flask will run on
EXPOSE 5000

# Set environment variables
ENV FLASK_APP=main_score.py

# Command to run the Flask application
CMD ["flask", "run", "--host=0.0.0.0"]
