version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    build:
      context: .
      dockerfile: dockerfile_flask
    container_name: myflask
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
