version: '3.8'


services:
  flask-app:
    image: main_core:01
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - ${VOLUME_PATH}:/scores.txt
